import localFont from "next/font/local";
import "./globals.css";
import Squares from './../components/common/Squares';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-900 bg-opacity-50`}
      >
        <Squares

          speed={0.1}
          squareSize={20}
          direction='diagonal' // up, down, left, right, diagonal
          borderColor='#000'
          hoverFillColor='#222'
        >


          {children}
        </Squares>
      </body>
    </html>
  );
}
